#!/bin/sh

if [ "$SUSPEND_METHOD" = "none" ] && \
    { [ -c /dev/pmu ] || grep -q mem /sys/power/state; } then
    SUSPEND_METHOD=kernel
    do_suspend()
    {
	if [ -c /dev/pmu ]; then
		pm-pmu --suspend
	else
		echo -n "mem" > /sys/power/state
	fi
    }
fi

if [ "$HIBERNATE_METHOD" = "none" ] && \
    [ -f /sys/power/disk ] && grep -q disk /sys/power/state; then
    HIBERNATE_METHOD=kernel
    do_hibernate()
    {
	[ -n "${HIBERNATE_MODE}" ] && \
	    grep -qw "${HIBERNATE_MODE}" /sys/power/disk && \
	    echo -n "${HIBERNATE_MODE}" > /sys/power/disk
	echo -n "disk" > /sys/power/state
    }
fi
