#!/bin/sh

# Note the lack of s2ram -- we just use kernel suspend.
# We were just duplicating the code done in 99video for no good reason.
# If we did use s2ram, we would override its internal processing with all
# our stuff anyways, and duplicate option processing code sucks.

if [ "$HIBERNATE_METHOD" = "none" ] && \
    [ -f /sys/power/disk ] && \
    grep -q disk /sys/power/state && \
    [ -c /dev/snapshot ] &&
    command_exists s2disk; then
    HIBERNATE_METHOD="uswsusp"

    do_hibernate()
    {
	s2disk
    }
fi


if [ "$SUSPEND_HYBRID_METHOD" = "none" ] && \
    grep -q mem /sys/power/state && \
    command_exists s2both && \
    [ "$HIBERNATE_METHOD" = "uswsusp" ]; then
    SUSPEND_HYBRID_METHOD=uswsusp

    do_suspend_hybrid()
    {
	s2both --force
    }
fi