#!/bin/sh

if [ "$HIBERNATE_METHOD" = "none" ] && \
    [ -f /sys/power/disk ] && \
    grep -q disk /sys/power/state && \
    [ -c /dev/snapshot ] &&
    command_exists s2disk; then
    HIBERNATE_METHOD="uswsusp"

    do_hibernate()
    {
	s2disk
    }
fi


if [ "$SUSPEND_HYBRID_METHOD" = "none" ] && \
    grep -q mem /sys/power/state && \
    command_exists s2both && \
    [ "$HIBERNATE_METHOD" = "uswsusp" ]; then
    SUSPEND_HYBRID_METHOD=uswsusp

    do_suspend_hybrid()
    {
	s2both --force
    }
fi
